### ISSUE TITLE
Bump to iOS 13 for GA Release

### ISSUE THREAD

**Issue by carlh** [iTwin/mobile-sdk#2]
The link below is one location, but we should update to 13 everywhere.

https://github.com/iTwin/mobile-sdk/blob/0bf9b239e24f0ed774edfd54829a306ddf31bb42/Package%40swift-5.5.swift#L14

**Comment by tcobbs-bentley** [comment]
@carlh Done in itwin-3 branch:

https://github.com/iTwin/mobile-sdk/commit/109d6eab1861acb9e7551df170d9c445901f6893
https://github.com/iTwin/mobile-sdk-samples/commit/86b86f3c1bcb5f92fc1f64aa19226b0946c2bb6d
